# AppVeyor Config
# http://www.appveyor.com/docs/lang/nodejs-iojs

# Don't run MSBuild
build: off

# Don't build tags
skip_tags: true

environment:
  nodejs_version: "10"

install:
  # Install Node
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - yarn --version

  # Install dependencies
  - yarn

test_script:
  # Postman
  - yarn test

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    template: "<{{buildUrl}}|Postman tests {{projectName}} {{buildVersion}} {{status}}>
      Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}:
      _{{commitMessage}}_"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true